configuration:
  title: Agile Process API
  description: An API dedicated to validate the Agile process followed by team with the help of Taiga.
  uri: https://peaceful-bastion-96327.herokuapp.com/taiga/

categories:
  Sprint:
    description: Information based on sprint in a project.
  User Story:
    description: Information based on user stories within a sprint.
  Task:
    description: Information based on tasks within user stories.

versions:
  v1.0:
    methods:
      Sprint Total Points:
        category: Sprint
        uri: sprint_story_points?slug={project}
        description: The story points that has been closed within a sprint

        request_parameters:
          project:
            type: string
            description: project slug name.

        response_body:
          type: object
          properties:
            story:
              type: array
              description: List of sprints and their story points
              items:
                type: Story


      Date Information:
        category: Sprint
        uri: sprint_date?slug={project}
        description: The date information of the user stories and sprint to validate which user stories are closed with in the sprint end date.

        request_parameters:
          project:
            type: string
            description: project slug name.

        response_body:
          type: object
          properties:
            date_info:
              type: array
              description: List of sprints and their user story date information.
              items:
                type: Date


      Sprint Information:
        category: Sprint
        uri: user_task_details?slug={project}
        description: The sprint information, user stories tasks and its references.

        request_parameters:
          project:
            type: string
            description: project slug name.

        response_body:
          type: object
          properties:
            sprint_user_task_details:
              type: array
              description: List of sprints and their user story date information.
              items:
                type: Sprint User Information
          

      Initial Task:
        category: Task
        uri: initial_task?slug={project}
        description: The initial tasks created in a user stories within a sprint.

        request_parameters:
          project:
            type: string
            description: project slug name.

        response_body:
          type: object
          properties:
            task_info:
              type: array
              description: List of sprints and their user story date information.
              items:
                type: Task


      User Story Information:
        category: User Story
        uri: sprint_user_story?slug={project}
        description: The number of open user story information in a sprint.

        request_parameters:
          project:
            type: string
            description: project slug name.

        response_body:
          type: object
          properties:
            sprint_user_story_info:
              type: array
              description: List of sprints and their user story date information.
              items:
                type: Closed User Story

      Wiki-Sprint analyzer:
        category: Sprint
        uri: listSprintDetails?projectslug={project}
        description: To compare date posted on MoM vs dates on taiga scrum board.
        item:
          request_parameters:
            project:
              type: string
              description: project slug name

          response_body:
            type: object
            properties:
              story:
                type: array
                description: Classfies sprint start on the basis of planned start vs actual start date.
                items:
                  type:  Sprint User Story

      Wiki parser:
        category: Sprint
        uri: wikiPage?projectslug={project}&wiki={wiki-page}
        description: To convert MoM from human readable to machine readable
        item:
          request_parameters:
            project:
              type: string
              description: project slug name & wiki slug name.

          response_body:
            type: object
            properties:
              story:
                type: array
                description: Parses MoM posted on a wiki page into keyvalue pairs
                items:
                  type: Sprint User Story


    types:

      Story:
        description: A story points information.
        item:
          type: object
          properties:
            closed_points:
              type: integer
              description: Total points closed in the sprint.

            name:
              type: string
              description: Name of the sprint.

            total_points:
              type: integer
              description: Total points in the sprint.

      Date:
        description: Date information of the sprint and user story.
        item:
          type: object
          properties:
            name:
              type: string
              description: Name of the sprint.
            sprint_end:
              type: string
              description: Sprint ending date.
            sprint_start:
              type: string
              description: Sprint starting date.
            user_story:
              type: array
              description: List of users story date details.
              items:
                type: User
      
      Task:
        description: Date information of the sprint and user story.
        item:
          type: object
          properties:
            name:
              type: string
              description: Name of the sprint.
            user_stories:
              type: array
              description: List of users story date details.
              items:
                type: Task Stories

      Sprint User Story:
        description: The sprint description and details.
        item:
          type: object
          properties:
            name:
              type: string
              description: Name of the sprint

            user_stories:
              type: array
              description: List of users story date details.
              items:
                type: Task Stories

      
      Sprint User Information:
        description: Date information of the sprint and user story.
        item:
          type: object
          properties:
            name:
              type: string
              description: Name of the sprint.
            user_stories:
              type: array
              description: List of users story date details.
              items:
                type: User Task Information


      User Task Information:
        description: The sprint description and details.
        item:
            type: object
            properties:
                Complete_Date:
                    type: string
                    description: User story completion date.

                Create_Date:
                    category: User Story
                    uri: userStoryCreateDate?projectslug={project}&sprint={sprint}
                    description: User story creation date.

                    request_parameters:
                        project:
                            type: string
                            description: project slug name
                        sprint:
                            type: integer
                            description: sprint number
                    response_body:
                        type: object
                        properties:
                            date_info:
                                type: array
                                description: User story creation date.
                                items:
                                    type: Date

                Description:
                    type: string
                    description: Detailed description of the user story.

                Ref_Num:
                    category: User Story
                    uri: list_of_userstories?projectslug={project}&sprint={sprint}
                    description: Reference number of the user story.

                    request_parameters:
                        project:
                            type: string
                            description: project slug name
                        sprint:
                            type: integer
                            description: sprint number
                            
                    response_body:
                        type: object
                        properties:
                            story:
                                type: array
                                description: Reference number of the user story.
                                items:
                                    type: integer

                Tasks:
                    category: Task
                    uri: task_of_userstory?projectslug={project}&userstory_id={user_story}
                    description: List of tasks.
              
                    request_parameters:
                        project:
                            type: string
                            description: project slug name
                        user_story:
                            type: integer
                            description: user story id
                
                    response_body:
                        type: object
                        properties:
                            task:
                                type: array
                                description: List of tasks.
                                items:
                                    type: Task Information

                
      User:
        description: A user
        item:
          type: object
          properties:
            created_date:
              type: string
              description: Creation date of user story
            description:
              type: string
              description: Details of the user story
            finish_date:
              type: string
              description: Finishing date of user story

      Closed User Story:
        description: Total number of closed user story information.
        item:
          type: object
          properties:
            closed_user_stories:
              type: integer
              description: Total number of closed user stories in a sprint.
            name:
              type: string
              description: The name of the sprint.
            no_of_user_stories:
              type: integer
              description: Total number of user stories in a sprint.
            open_user_stories:
              type: integer
              description: Total number of open user stories in a sprint.


      Task Stories:
        description: A initial tasks in a user story
        item:
          type: object
          properties:
            Description:
              type: string
              description: user story detailed description.
            Initial_task:
              type: integer
              description: Total number of initial task.
          

      Task Information:
        description: A initial tasks in a user story
        item:
          type: object
          properties:
            Complete_Date:
              type: string
              description: Task completion date.

            Create_Date:
              type: string
              description: Task creation date.

            Description:
              type: string
              description: Detailed description of the Task.

            Ref_Num:
              type: integer
              description: Reference number of the Task.

      User_task_History:
        category: User Task. 
        description: History of user tasks to different statuses in a sprint.
        uri: historyOfTasks?projectslug={project}&sprint={sprintno}

        request_parameters:
                        project:
                            type: string
                            description: project slug name
                        sprintno:
                            type: integer
                            description: sprint number

        response_body:
                        type: object
                        properties:
                            task:
                                type: List
                                description: List of tasks and the dates when they were moved to different status.
                                items:
                                    type: Date

      User_task_Information:
        category: User Task. 
        description: user Task information for a particular sprint.
        uri: User_task_Information?projectslug={project}&sprint={sprintno}

        request_parameters:
                        project:
                            type: string
                            description: project slug name
                        sprintno:
                            type: integer
                            description: sprint number

        response_body:
                        type: object
                        properties:
                            task:
                                type: Integer
                                description: Task number in a particular sprint
                                items:
                                    type: List
                                    description: Information about a Task in that sprint.
                                    properties:
                                        user_task:
                                          type: String
                                          description: User_task name.
                                        user_task_created_at:
                                          type: Date
                                          description: user_task created date.
                                         
        Team_members_info:
                category: team info. 
                description: Information about team members working.
                uri: teammemberinfo?projectslug={project}

                 request_parameters:
                                project:
                                    type: string
                                    description: project slug name


                 response_body:
                                type: object
                                properties:
                                    user_details:
                                        name: name of user
                                        username: username of the user
                                        role_name: role of the member
                                        full_name_display: display name on taiga
                                        id: taiga id


        User_Story_Points_Information:
                category: User story points information. 
                description: user Task information for a particular sprint.
                uri: memberuserstorypointsinfo?projectslug={project}&sprint={sprintno}

                request_parameters:
                                project:
                                    type: string
                                    description: project slug name
                                sprintno:
                                    type: integer
                                    description: sprint number

                response_body:
                                type: object
                                properties:
                                    Story:
                                        type: Integer
                                        description: User Story number in a particular sprint
                                        items:
                                            type: List
                                            description: Information about User Story in that sprint.
                                            properties:
                                                User_Story:
                                                  US_name: String
                                                  US_points: User Story points.
                                                  Task:
                                                    assigned to: task assigned which user.
                                                user_story_created_at:
                                                  type: Date
                                                  description: user_story created date.



        User_Task_progress_with_days_info:
                category: User tasks progress and days array. 
                description: User tasks progress and days array in particular sprint.
                uri: UserTaskchangestatus?projectslug={project}&sprint={sprintno}

                request_parameters:
                                project:
                                    type: string
                                    description: project slug name
                                sprintno:
                                    type: integer
                                    description: sprint number

                response_body:
                                type: object
                                properties:
                                    Story:
                                        type: Integer
                                        description: User Story number in a particular sprint
                                        items:
                                            type: List
                                            description: Information about User Story in that sprint.
                                            properties:
                                                User_Story:
                                                  created_date: String
                                                  status_change:
                                                    New -In progress: date when task was moved to inprogress
                                                    In progress- Ready for test: date when task was moved to ready to test
                                                    Ready for test- Closed: date when task was moved to ready to closed
                                                Days:
                                                  [Array with number of days spent at each stage]



                                        




